version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - build_consumer:
          context: aws
      - build_provider:
          context: aws
  weekly:
    triggers:
      # Keep the wheels greased (keep builds from aging out of Firebase)
      - schedule:
          cron: "8 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - build_consumer:
          context: aws
      - build_provider:
          context: aws

orbs:
  android: circleci/android@0.2.1

jobs:
  build_consumer:
    working_directory: ~/code/OpenCabConsumer
    executor: android/android
    steps:
      - checkout:
          path: ~/code
      - run:
          name: Install Firebase credentials
          command: echo "$GCLOUD_SERVICE_ACCOUNT_JSON" > ~/gcloud.json
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Create release build
          command: ./gradlew assembleDebug
      - run:
          name: Upload build to Firebase
          command: GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json ./gradlew appDistributionUploadDebug

  build_provider:
    working_directory: ~/code/OpenCabProvider
    executor: android/android
    steps:
      - checkout:
          path: ~/code
      - run:
          name: Install Firebase credentials
          command: echo "$GCLOUD_SERVICE_ACCOUNT_JSON" > ~/gcloud.json
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Create release build
          command: ./gradlew assembleDebug
      - run:
          name: Upload build to Firebase
          command: GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json ./gradlew appDistributionUploadDebug
